apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: "kinoko-takenoko-django"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: "kinoko-takenoko-django"
  type: NodePort
