apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: django
        image: kinoko-takenoko-django/app-dev:latest
        command: ["bash", "-c"]
        args:
        - |
          python manage.py makemigrations;python manage.py migrate;
        env:
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_NAME
          value: "postgres"
        envFrom:
        - configMapRef:
            name: django-env
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
