# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [test]
  pull_request:
    branches: [test]

env:
  DOCKER_CONFIG: '${{ github.workspace }}/.docker'
  MANAGED_IDENTITY_CLIENT_ID: '1d9589c5-9f66-400a-8733-c0cb657dc0ed'

  TEST_IMAGE_NAME: 'proxy.trendmicro:5000/shinseidx/densin-apache:${{ github.sha }}'
  CACHE_IMAGE_NAME: 'proxy.trendmicro:5000/shinseidx/densin-apache:cache'
  PUSH_IMAGE_NAME: 'pjpeshinseidxacr.azurecr.io/densin-apache:1.0.9'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/python/requirements.txt
    - name: Django app url shortner test
      run: python djangoserver/manage.py test urlshortner
      env:
        DB_HOST: 127.0.0.1
        DB_PASSWORD: postgres
        DB_USER: postgres
        REDIRECT_DOMAINS: red.localhost:3000/
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: checkout
      - name: Hadolint the Dockerfile
        run: docker run --rm -i -v $PWD/checkout/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < checkout/Dockerfile
