# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [test]
  pull_request:
    branches: [test]

env:
  DOCKER_CONFIG: '${{ github.workspace }}/.docker'
  MANAGED_IDENTITY_CLIENT_ID: ''

  TEST_IMAGE_NAME: ''
  CACHE_IMAGE_NAME: ''
  PUSH_IMAGE_NAME: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/python/requirements.txt
    - name: Django app url shortner test
      run: python manage.py test urlshortner
      env:
        DATABASE_ENGINE: django.db.backends.sqlite3
        DATABASE_NAME: postgres
        REDIRECT_DOMAINS: red.localhost:3000/

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: checkout
      - name: Hadolint the Dockerfile
        run: docker run --rm -i -v $PWD/checkout/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < checkout/Dockerfile
